
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 01 12:34:32 CEST 2016
//----------------------------------------------------

package edu.uap;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LT = 19;
  public static final int ELSE = 6;
  public static final int THEN = 5;
  public static final int SEMI = 20;
  public static final int IN = 3;
  public static final int RBRA = 10;
  public static final int IF = 4;
  public static final int LBRA = 9;
  public static final int GT = 18;
  public static final int ID = 22;
  public static final int SUB = 13;
  public static final int COMMA = 21;
  public static final int EOF = 0;
  public static final int MULT = 14;
  public static final int DIV = 15;
  public static final int ADD = 12;
  public static final int CONST = 23;
  public static final int error = 1;
  public static final int LET = 2;
  public static final int ASSIGN = 11;
  public static final int EQ = 16;
  public static final int RPAR = 8;
  public static final int NEQ = 17;
  public static final int LPAR = 7;
}

